### ISSUE TITLE
Cannot find module '../lib/completion'

### ISSUE THREAD

**Issue by ghost** [anatoo/gulper#3]
I installed gulper with `npm i -g gulper`, but when I run it on one of my projects, I get the following error:

```
Error: Cannot find module '../lib/completion'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/samvv/projects/comet/comet/node_modules/.bin/gulp:13:18)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.nodeDevHook [as .js] (/usr/local/lib/node_modules/gulper/node_modules/node-dev/lib/hook.js:43:7)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
```

**Comment by anatoo** [comment]
Hi @samvv
I tried but can't reproduce that error in my project.
Could you provide more information to reproduce that error?

**Comment by ghost** [comment]
Hmm strange ... I simply used `gulper`. Maybe I missed something really silly. I'll post more tomorrow.

**Comment by jhogendorn** [comment]
Hi, gulper does not work for me now either.

Node 6.1.0
NPM 3.8.6
Gulp 3.9.1

**Comment by anatoo** [comment]
Fixed probably. Please try new version.

**Comment by jhogendorn** [comment]
Hi @anatoo thanks so much for this.

gulper now does initial run fine, however it seems to hang when restarting after a gulpfile change, simply printing 'Restarting' and no further actions.

Node 6.9.2, NPM 3.10.9, Gulp 3.9.1, Gulper 0.1.3

**Comment by anatoo** [comment]
@jhogendorn Hmm... Could you share your gulpfile?

**Comment by jhogendorn** [comment]
Uh, in theory yes, but I don't think it would be helpful as all the 'meat' of our gulp setup is in a private package and the gulpfile is essentially just config.

could I perhaps run gulper in a verbose debug mode of some kind?

**Comment by anatoo** [comment]
@jhogendorn OK, could you run this command in your project?

```bash
npm install -g node-dev
node-dev $(which gulp) your-task-name
```

If it does not work, it should be node-dev's problem.

**Comment by jhogendorn** [comment]
Yep same behaviour, i'll go have a chat with the node-dev people :) thanks!
